[package]
name = "calculate_stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.0.0"
clap = {version = "4.0.0", features = ["cargo"]}
rayon = "1.6.0"